<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
		    <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title')</title>
        <meta name="Description" content="Real Estate Title Company in DC, Maryland and Virginia.">
        <meta name="Keywords" content="real estate title company maryland, title and escrow services, best title company maryland, real estate title company near me">

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "LocalBusiness",
          "name" : "Heritage Title",
          "image" : "{{ asset('images/logos/HeritageTitle.png') }}",
          "telephone" : "866-913-4095",
          "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "175 Admiral Cochrane Drive, Suite 111",
            "addressLocality" : "Annapolis",
            "addressRegion" : "MD",
            "postalCode" : "21401"
          },
          "openingHoursSpecification" : {
            "@type" : "OpeningHoursSpecification",
            "dayOfWeek" : {
              "@type" : "DayOfWeek",
              "name" : "Monday - Friday"
            }
          },
          "url" : "www.heritagetitlemd.com"
        }
        </script>

        <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
    		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
    		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <!-- Custom styles for this template -->
        <link href="css/agency.min.css" rel="stylesheet">
		
    </head>
    <body id="page-top">

      @include('includes.navbar')

      @yield('content')

      @include('includes.footer')

      <!-- Bootstrap core JavaScript -->
      <script src="{{ asset('js/app.js') }}"></script>

      <!-- Plugin JavaScript -->
      <script src="{{ asset('js/jquery.easing.min.js') }}"></script>

      <!-- Contact form JavaScript -->
      <script src="{{ asset('js/jqBootstrapValidation.js') }}"></script>
      <script src="{{ asset('js/contact_me.js') }}"></script>

      <!-- Custom scripts for this template -->
      <script src="{{ asset('js/agency.min.js') }}"></script>

    </body>
</html>